### PR TITLE
Update autodoc for SDK APIs

### PR DESCRIPTION
**Pull request by joshua-oss**
Re-ordered and filtered to show mean public APIs.

Note that this doc update requires typo in #368 to be fixed

### CODE REVIEW

**Review by lurosenb — APPROVED** [review]
Awesome Joshua, thanks for the docs!

**Comment by pdurbin** [comment]
Heads up that I had to remove most of this pull request. We were seeing build issues in #32 so in pull request #34 I removed these pages that weren't building:

- smartnoise/api-reference/opendp.smartnoise.synthesizers.html
- smartnoise/api-reference/opendp.smartnoise.synthesizers.pytorch.nn.html

**Comment by joshua-oss** [comment]
Ah, there was a note in the PR that this requires: https://github.com/opendp/smartnoise-sdk/pull/368, which has been merged to main but not PyPi.

**Comment by pdurbin** [comment]
@joshua-oss gotcha. Thanks. Once it's on PyPi, let's try again.

**Pull request merged**
