### PR TITLE
Added back synthesizers from PR #25

### PR DESCRIPTION
**Pull request by lurosenb**
Now that the newest smartnoise release (0.1.4.1) fixes the issue with MWEM docstring (thanks for finding @pdurbin ), we could add back the synthesizers docs that @joshua-oss had added in #25 .

**Note**: If we add this back, we will need to add 3 dependencies to our reqs (torch, opacus, ctgan), as they are not default reqs in smartnoise by design.

### CODE REVIEW

**Review by pdurbin — CHANGES_REQUESTED** [review]
@lurosenb thanks for the pull request. Can you please take a look at requirements.txt again? I got the following error when trying to pip install them:

`ERROR: Could not find a version that satisfies the requirement ctgan==0.2.2.dev1 (from versions: 0.1.0.dev0, 0.1.0, 0.2.0.dev0, 0.2.0, 0.2.1.dev0, 0.2.1, 0.2.2.dev0)`
`ERROR: No matching distribution found for ctgan==0.2.2.dev1`

I did a fresh clone of the repo for this test.

**Comment by lurosenb** [comment]
> @lurosenb thanks for the pull request. Can you please take a look at requirements.txt again? I got the following error when trying to pip install them:
> 
> `ERROR: Could not find a version that satisfies the requirement ctgan==0.2.2.dev1 (from versions: 0.1.0.dev0, 0.1.0, 0.2.0.dev0, 0.2.0, 0.2.1.dev0, 0.2.1, 0.2.2.dev0)`
> `ERROR: No matching distribution found for ctgan==0.2.2.dev1`
> 
> I did a fresh clone of the repo for this test.

Hi @pdurbin ! Huh - that's weird - I am able to install this release: https://pypi.org/project/ctgan/0.2.2.dev1/ 

Just verified that 0.2.2.dev0 works too - swapping to that version, hopefully this will work for you!

**Comment by pdurbin** [comment]
@lurosenb I just tested ec3b307 (fresh clone again) and Pandas won't build. Very strange. Here's the terminal output: [ec3b307.txt](https://github.com/opendp/opendp-documentation/files/6658527/ec3b307.txt)

**Comment by lurosenb** [comment]
> @lurosenb I just tested [ec3b307](https://github.com/opendp/opendp-documentation/commit/ec3b3079773880c60a765026effda205b959b1ef) (fresh clone again) and Pandas won't build. Very strange. Here's the terminal output: [ec3b307.txt](https://github.com/opendp/opendp-documentation/files/6658527/ec3b307.txt)

Very weird! I just realized - you are on a mac - very difficult for me to debug on my windows machine using wsl...perhaps try using a fresh conda env with python=3.8, and swap in a different ctgan version (like 0.2.4 perhaps?) - sorry for all this hassle

**Comment by joshua-oss** [comment]
I had problems installing on Mac as well.  What fixed it for me was:

'''
rm -rf ~/miniconda3

vim ~/.zshrc

(delete the conda init lines, save, and restart)

(download and install anaconda GUI)

conda update conda

conda update pip

pip install --upgrade setuptools

pip install ctgan==0.2.2.dev

pip install --use-feature=2020-resolver opacus==0.9.0
'''

**Comment by pdurbin** [comment]
@lurosenb @joshua-oss sorry, I was busy with a conference all last week.

I appreciate the Mac tips but this pull request fails not only on my Mac but within GitHub Actions as well (same error). Here's a screenshot from https://github.com/pdurbin/opendp-documentation/runs/2888067000?check_suite_focus=true

Screen Shot 2021-06-22 at 2 45 32 PM

On a related note, I created #44 because we should have more automation to determine if pull requests build or not.

If you'd like to do the same test I did, here are the steps:

- Fork this repo.
- Enable GitHub Actions (disabled on forks by default, apparently)
- Set up GitHub Pages
- Push a commit to the gh-pages branch (not sure why this is necessary)
- Make sure the docs appear in your fork, for me it's http://pdurbin.github.io/opendp-documentation
- Merge the branch into "latest"
- Push latest to your fork (I used `git push pdurbin latest`)
- Check the GitHub Action to see if there are any errors

I hope this helps until we get more automation set up. Once you get your branch building on GitHub Actions, please let me know!

**Comment by pdurbin** [comment]
@lurosenb @joshua-oss phew! Merged! These pages look good to me:

- https://docs.opendp.org/en/latest/smartnoise/api-reference/opendp.smartnoise.synthesizers.html
- https://docs.opendp.org/en/latest/smartnoise/api-reference/opendp.smartnoise.synthesizers.pytorch.nn.html

@raprasad helped me figure out that as of this pull request they docs don't build on Python 3.9, which is what I've been using on my laptop. In 380ea57 I explained in the README that Python 3.8 is required, which is kind of a bummer. If you know of any issues we can track to know when we'll be able to support newer versions of Python, please drop some links here.

Thanks for the pull request! I'm glad that the API docs are more complete now.

**Comment by joshua-oss** [comment]
Oh, wow, I don't think I would have figured that out.  Strangely enough, the docs seem to be building OK with Python 3.9 on the integration tests on SDK side.  For example, here's a run from a a few minutes ago, and I can drill into the output and see that synthesizers docs were built:

https://github.com/opendp/smartnoise-sdk/runs/2900641999?check_suite_focus=true

The YAML I use to test the build is based on the Conda template, and tests 3.7, 3.8, and 3.9:

https://github.com/opendp/smartnoise-sdk/blob/main/.github/workflows/docs.yml

**Pull request merged**
